### ISSUE TITLE
WP Namespace version 1.2

### ISSUE THREAD

**Issue by natcoxall** [benlakey/press_sharp#2]
I recently implemented this API against a wordpress export file with namespace "http://wordpress.org/export/1.2/" rather than the hard-coded "http://wordpress.org/export/1.1/". It means that no child elements were being returned in the API methods.

If the blog class could infer the NS from the document instead that would resolve this.

Great utility though, really please to have found it, saved me loads of time :)

**Comment by benlakey** [comment]
Thanks for the report. I haven't written much C# since 3 years ago and it was for this project. I may get around to modifying it like you mentioned but if you'd like to send a pull-request that fixes it that'd be welcome too.
